// File generated by FlutterFire CLI.
// ⚠️ THIS IS A PLACEHOLDER. Run `flutterfire configure` in the project root
// to regenerate this file with your real Firebase project's credentials.
// See the setup instructions for the exact command.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform. '
          'Run `flutterfire configure` to add support for it, or use '
          'another platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'REPLACE_ME',
    appId: 'REPLACE_ME',
    messagingSenderId: 'REPLACE_ME',
    projectId: 'mzingi-invest',
    authDomain: 'mzingi-invest.firebaseapp.com',
    storageBucket: 'mzingi-invest.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'REPLACE_ME',
    appId: 'REPLACE_ME',
    messagingSenderId: 'REPLACE_ME',
    projectId: 'mzingi-invest',
    storageBucket: 'mzingi-invest.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'REPLACE_ME',
    appId: 'REPLACE_ME',
    messagingSenderId: 'REPLACE_ME',
    projectId: 'mzingi-invest',
    storageBucket: 'mzingi-invest.appspot.com',
    iosBundleId: 'com.mzingi.invest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'REPLACE_ME',
    appId: 'REPLACE_ME',
    messagingSenderId: 'REPLACE_ME',
    projectId: 'mzingi-invest',
    storageBucket: 'mzingi-invest.appspot.com',
    iosBundleId: 'com.mzingi.invest',
  );
}
